### ISSUE TITLE
Low-budget results

### ISSUE THREAD

**Issue by MingjieChen** [bootphon/zerospeech2021_baseline#1]
Hello, 

The official website said the low-budget model training is only with one GPU and within 3 days.

So is it possible to provide results from the baseline models being trained under the low-budget situations?

Or can you give some suggestions about the configs and hyper-parameters (i.e. sizeWindow) for low-budget baseline training?

Thanks

**Comment by mmmaat** [comment]
Hi, we recently published the results for all the baselines and toplines: https://zerospeech.com/2021/results.html.
