### ISSUE TITLE
sampling rate is different between training and test data

### ISSUE THREAD

**Issue by MingjieChen** [bootphon/zerospeech2021_baseline#3]
Hi,

I just noticed that the sampling rate of librispeech training data (.flac) files are 16000, however the sampling rate of provided testing data (.wav) files are 22050.

I am just wondering will it cause a problem?

Thanks

**Comment by mmmaat** [comment]
Hi,

We thought we resampled the whole dataset to 16kHz... Do you have example of such files?
It will not cause a problem. First you are free to resample them if you want. Second the baseline system works well with it (see https://zerospeech.com/2021/results.html).

Thank you
