### ISSUE TITLE
How to calculate ABX score?

### ISSUE THREAD

**Issue by EmreOzkose** [bootphon/zerospeech2021_baseline#6]
Hi!

I followed these steps:
1. CPC training,
2. Kmeans training
3. LSTM training

After these steps, I build one-hot vectors from quantized outputs. Now, I want to calculate ABX score, but couldn't find how to do in this repo.

Note: I know that ABX score is only realated to features, but I wanted to say that I followed the pipeline, but couldn't get how to evaluate.

**Comment by mmmaat** [comment]
Hi, the evaluation part of the challenge is in [this repo](https://github.com/bootphon/zerospeech2021).
