### ISSUE TITLE
Checkpoints not found 404 error

### ISSUE THREAD

**Issue by SolomidHero** [bootphon/zerospeech2021_baseline#7]
```
curl https://download.zerospeech.com/2021/baseline_checkpoints.tar.gz
```
result:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
```

**Comment by nhamilakis** [comment]
Hello, sorry i moved the files and forgot to update this git, 
the checkpoint files can be downloaded at [http://download.zerospeech.com/models/2021_baseline.checkpoints.tar.gz](http://download.zerospeech.com/models/2021_baseline.checkpoints.tar.gz)

I will update the readme with the correct URLs
